### ISSUE TITLE
Missing DeadByDaylight.bat

### ISSUE THREAD

**Issue by KasaiKonoru** [Preston159/dbd-server#19]
where is this file? And there is no DefaultEngine.ini file in dbd folder

**Comment by Midnoclose** [comment]
Those files are not a part of this repository. They are a part of the Dead By Daylight game files.

**Comment by KasaiKonoru** [comment]
> Those files are not a part of this repository. They are a part of the Dead By Daylight game files.

´But there is no DeadByDaylight/Config folder. Where I can find that?
