### ISSUE TITLE
event

### ISSUE THREAD

**Issue by FoudreTeam** [Preston159/dbd-server#5]
it's not a bug report but a feature request,
I propose a function that can make sure to activate events (lunar event, halloween event or christmas event)

**Comment by ettfemnio** [comment]
I had actually previously thought about this, but if I'm not mistaken it requires the ability to encrypt custom data using BHVR's encryption method. I can look into this again, but I can't promise anything.

If anyone else wants to lend a hand on this, I've implemented the decryption algorithm [here](https://github.com/Preston159/dbd-server/blob/11d086aaf205c1eef5ad3d730b96257d5889f8a7/src/saveman.ts#L14) and it just needs to be reversed.

**Comment by ettfemnio** [comment]
I've figured out the encryption! I'll look more into this over the next couple days.

Edit: Don't get your hopes up just yet. The game seems to be ignoring the data I send to it. I'll investigate more.

**Comment by ettfemnio** [comment]
Closing, as this has been done in 1.4.0. I plan on improving it a bit, but it's functional as of now.
